Repository xkarox/P_3FA132_Gruppe_3, pull requests merged in 2025-02, with the labels that each got.

#150 #149_jddk_refactor_base_service
  src/main/java/dev/hv/database/DatabaseConnection.java
  src/main/java/dev/hv/database/services/AbstractBaseService.java
  src/main/java/dev/hv/database/services/CustomerService.java
  src/main/java/dev/hv/database/services/ReadingService.java
  src/main/java/dev/hv/model/classes/Customer.java
  src/test/java/dev/hv/database/mocks/MockTableObject.java
  src/test/java/dev/hv/database/mocks/MockTableObject2.java
Labels: Ready for review

#147 #146_jddk_implement_in_abstract_base_class
  src/main/java/dev/server/validator/CustomerJsonSchemaValidatorService.java
  src/main/java/dev/server/validator/CustomerWithReadingsJsonSchemaValidatorService.java
  src/main/java/dev/server/validator/JsonSchemaValidatorServiceBase.java
  src/main/java/dev/server/validator/ReadingJsonSchemaValidationService.java
Labels: Ready for review

#129 Feature 99 borris123 implement csv parser
  .github/workflows/maven.yml
  src/main/java/dev/hv/csv/CsvFormatter.java
  src/main/java/dev/hv/csv/CsvParser.java
  src/main/java/dev/server/Main.java
  src/test/java/dev/hv/csv/CsvFormatterTest.java
  src/test/java/dev/hv/csv/CsvParserTest.java
Labels: enhancement, Ready for review, feature

#142 refactor_141_xkarox_refactor_Spring_Boot_to_Jakarta
  pom.xml
  src/main/java/dev/hv/Utils.java
  src/main/java/dev/server/Main.java
  src/main/java/dev/server/Server.java
  src/main/java/dev/server/config/JacksonConfig.java
  src/main/java/dev/server/config/JerseyConfig.java
  src/main/java/dev/server/controller/CustomerController.java
  src/main/java/dev/server/controller/DatabaseController.java
  src/main/java/dev/server/controller/ReadingController.java
  src/main/java/dev/server/filter/CORSFilter.java
  src/main/java/dev/server/filter/LoggingFilter.java
  src/main/java/dev/server/filter/RequestIdFilter.java
  src/main/resources/application.properties
  src/main/resources/logback.xml
  src/test/java/dev/server/MainTest.java
  src/test/java/dev/server/controller/CustomerControllerTest.java
  src/test/java/dev/server/controller/DatabaseControllerTest.java
  src/test/java/dev/server/controller/ReadingControllerTest.java
Labels: Ready for review, nice2have, refactor
